### ISSUE TITLE
Run `start_work()` after `toggle_pause()` will cause a semantic error.

### ISSUE THREAD

**Issue by nyngwang** [jackMort/pommodoro-clock.nvim#1]
Thanks for creating this beautiful plugin :) I noticed a little bug after playing with it for a while: if I `start_work()` then `toggle_pause()` and `start_work()` again, then while the clock is still ticking the "II PAUSED" sign is still there. After that its meaning gets reversed: paused now means ongoing and ongoing now means paused.

**Comment by jackMort** [comment]
Thanks for letting me know, it's already fixed
