### ISSUE TITLE
Make Voice Lines Optional

### ISSUE THREAD

**Issue by sbreining** [jackMort/pommodoro-clock.nvim#3]
The ability to toggle the voice line would be great. Or, even better, it would be awesome to have short bell sounds. The available config options could be `'voice' | 'bell' | 'none'`. And a possible config could look like the following:
```lua
setup({
  modes = { ... }
  sound = 'bell'
  animation_duration = 300
  animation_fps = 30
})
```

**Comment by jackMort** [comment]
I added option to disable sound, for the future I'll try to add bell functionality but need to find some solution for that
